eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: SNAILMALL-CONFIG-SERVER
      profile: dev
