spring:
  rabbitmq:
    host: 111.231.119.253
    port: 5672
    username: root
    password: root
  datasource:
     name: dev
     url: jdbc:mysql://127.0.0.1:3306/snailmall
     username: root
     password: root
redis:
    host: 111.231.119.253
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
test:
  name: test-9
