eureka:
  instance:
    ip-address: 47.101.31.197
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://106.14.163.235:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 111.231.119.253
    port: 5672
    username: root
    password: root
zk:
  host: 111.231.119.253
